import { mkdir } from 'node:fs/promises'
import { basename } from 'node:path'
import * as l from '~/utils/logger'
import type { GeminiImageModel, Step5Metadata } from '~/types'
import { logMediaGenerationStatus } from '~/cli/commands/process-steps/generation-command-utils'
import { isNativeGeminiImageModel } from '~/cli/commands/setup-and-utilities/models/model-options'
import { readEnv } from '~/utils/validate/env-utils'
import { geminiGenerateContent, geminiGenerateImages } from '~/utils/gemini/gemini-rest'
import { imageReferenceToInlineDataPart } from '../../image-utils/image-inputs'
import { getProviderReturnedModel } from '../../image-utils/image-output'

export const runGeminiImageGen = async (
  prompt: string,
  outputDir: string,
  options: {
    model: GeminiImageModel
    mode?: 'generation' | 'edit' | undefined
    inputs?: string[] | undefined
    aspectRatio?: string | undefined
    imageSize?: string | undefined
    imageCount?: number | undefined
    responseMode?: 'image' | 'text-image' | undefined
    personGeneration?: string | undefined
    searchGrounding?: boolean | undefined
  }
): Promise<{ imagePaths: string[], metadata: Step5Metadata }> => {
  const apiKey = readEnv('GEMINI_API_KEY')
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY environment variable is required')
  }

  const startTime = Date.now()
  const imagePaths: string[] = []
  const mode = options.mode ?? 'generation'
  let providerReturnedModel: string | undefined
  let groundingMetadata: unknown

  await mkdir(outputDir, { recursive: true })

  if (isNativeGeminiImageModel(options.model)) {
    logMediaGenerationStatus(l, {
      mediaType: 'image',
      provider: 'gemini',
      model: options.model,
      status: 'started',
      detail: mode === 'edit' ? 'native image edit' : 'native image'
    })
    const inputParts = await Promise.all((options.inputs ?? []).map(imageReferenceToInlineDataPart))
    const responseModalities = options.responseMode === 'text-image' ? ['TEXT', 'IMAGE'] : ['IMAGE']

    const response = await geminiGenerateContent(apiKey, {
      model: options.model,
      contents: [{ text: prompt }, ...inputParts],
      generationConfig: {
        responseModalities,
        ...(options.aspectRatio || options.imageSize ? {
          imageConfig: {
            ...(options.aspectRatio ? { aspectRatio: options.aspectRatio } : {}),
            ...(options.imageSize ? { imageSize: options.imageSize } : {})
          }
        } : {})
      },
      ...(options.searchGrounding ? { tools: [{ googleSearch: {} }] } : {})
    })
    providerReturnedModel = getProviderReturnedModel(options.model, response)
    groundingMetadata = response.candidates?.find((candidate) => candidate.groundingMetadata !== undefined)?.groundingMetadata

    const candidates = response.candidates ?? []
    if (candidates.length === 0 || !candidates[0]?.content?.parts) {
      throw new Error('No image content in Gemini response')
    }

    let imageIndex = 0
    for (const part of candidates[0].content.parts) {
      if (part.inlineData && part.thought !== true) {
        const imageData = part.inlineData.data
        if (!imageData) continue
        const outputPath = imageIndex === 0
          ? `${outputDir}/generated-image.png`
          : `${outputDir}/generated-image-${imageIndex + 1}.png`
        await Bun.write(outputPath, Buffer.from(imageData, 'base64'))
        imagePaths.push(outputPath)
        imageIndex++
      }
    }
  } else {
    logMediaGenerationStatus(l, {
      mediaType: 'image',
      provider: 'gemini',
      model: options.model,
      status: 'started',
      detail: 'imagen'
    })
    const numberOfImages = options.imageCount ?? 1

    const response = await geminiGenerateImages(apiKey, {
      model: options.model,
      prompt,
      numberOfImages,
      ...(options.aspectRatio ? { aspectRatio: options.aspectRatio } : {}),
      ...(options.imageSize ? { imageSize: options.imageSize } : {}),
      ...(options.personGeneration ? { personGeneration: options.personGeneration } : {})
    })

    const generatedImages = response.generatedImages ?? []
    for (let i = 0; i < generatedImages.length; i++) {
      const generated = generatedImages[i]
      const imageBytes = generated?.image?.imageBytes
      if (!imageBytes) continue
      const outputPath = i === 0
        ? `${outputDir}/generated-image.png`
        : `${outputDir}/generated-image-${i + 1}.png`
      await Bun.write(outputPath, Buffer.from(imageBytes, 'base64'))
      imagePaths.push(outputPath)
    }
  }

  if (imagePaths.length === 0) {
    throw new Error('No images were generated by Gemini')
  }

  const processingTime = Date.now() - startTime
  const primaryPath = imagePaths[0] as string
  const primaryFile = Bun.file(primaryPath)
  const imageFileSize = primaryFile.size

  logMediaGenerationStatus(l, {
    mediaType: 'image',
    provider: 'gemini',
    model: options.model,
    status: 'completed',
    processingTimeMs: processingTime,
    outputCount: imagePaths.length
  })

  const metadata: Step5Metadata = {
    imageService: 'gemini',
    imageModel: options.model,
    processingTime,
    imageCount: imagePaths.length,
    imageFileNames: imagePaths.map((imagePath) => basename(imagePath)),
    imageFileSize,
    imageWidth: undefined,
    imageHeight: undefined,
    requestMode: mode,
    ...(providerReturnedModel ? { providerReturnedModel } : {}),
    ...(groundingMetadata !== undefined ? { groundingMetadata } : {})
  }

  return { imagePaths, metadata }
}
