import { expect, test } from 'bun:test'
import { runCommand } from '../../test-utils/test-helpers'

const helpEnv = { NO_COLOR: '1' }

const getSection = (output: string, heading: string, nextHeading?: string): string => {
  const start = output.indexOf(heading)
  expect(start).toBeGreaterThanOrEqual(0)

  const sectionStart = start + heading.length
  const end = nextHeading ? output.indexOf(nextHeading, sectionStart) : output.length
  expect(end).toBeGreaterThan(sectionStart)

  return output.slice(sectionStart, end)
}

const getFlagGroupSection = (output: string, label: string): string => {
  const heading = `\n  ${label}\n`
  const start = output.indexOf(heading)
  expect(start).toBeGreaterThanOrEqual(0)

  const sectionStart = start + heading.length
  const tail = output.slice(sectionStart)
  const nextGroup = tail.match(/\n  [A-Za-z0-9][^\n]*\n/)
  const globalFlags = output.indexOf('\nGlobal Flags\n', sectionStart)
  const nextGroupEnd = nextGroup?.index === undefined ? output.length : sectionStart + nextGroup.index
  const globalFlagsEnd = globalFlags === -1 ? output.length : globalFlags
  return output.slice(sectionStart, Math.min(nextGroupEnd, globalFlagsEnd))
}

test('root help groups setup utilities separately from processing commands', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)

  const setupSection = getSection(result.stdout, '  Setup & Utilities\n', '  Processing & Generation\n')
  const processingSection = getSection(result.stdout, '  Processing & Generation\n')

  expect(setupSection).toContain('    links')
  expect(setupSection).toContain('    setup')
  expect(setupSection).toContain('    resume')
  expect(processingSection).toContain('    write')
  expect(processingSection.indexOf('    video')).toBeLessThan(processingSection.indexOf('    music'))
  expect(processingSection).not.toContain('    lyrics')
  expect(processingSection).not.toContain('    stt')
  expect(processingSection).not.toContain('    ocr')
  expect(processingSection).not.toContain('    links')
  expect(processingSection).not.toContain('    resume')
})

test('metadata help groups document, output, article, and batch flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'metadata', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(getFlagGroupSection(result.stdout, 'Document Options')).toContain('--password')
  expect(getFlagGroupSection(result.stdout, 'Metadata Output')).toContain('--markdown')
  expect(getFlagGroupSection(result.stdout, 'Metadata Output')).toContain('--save')
  expect(getFlagGroupSection(result.stdout, 'Article Extraction')).toContain('--url-provider')
  expect(getFlagGroupSection(result.stdout, 'Batch Processing')).toContain('--batch-limit')
})

test('extract help exposes shared batch and all-provider flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'extract', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  const providerSection = getFlagGroupSection(result.stdout, 'Provider Selection')
  const transcriptionSection = getFlagGroupSection(result.stdout, 'Transcription / STT')
  const documentSection = getFlagGroupSection(result.stdout, 'OCR / Document Extraction')
  const articleSection = getFlagGroupSection(result.stdout, 'Article Extraction')
  const batchSection = getFlagGroupSection(result.stdout, 'Batch Processing')
  const epubSection = getFlagGroupSection(result.stdout, 'EPUB Inspect')
  const transcriptVideoSection = getFlagGroupSection(result.stdout, 'Transcript Video')
  const pricingSection = getFlagGroupSection(result.stdout, 'Pricing')

  expect(providerSection).toContain('--provider')
  expect(providerSection).toContain('--all-providers')
  expect(providerSection).toContain('--provider-concurrency')
  expect(providerSection).toContain('--local-concurrency')
  expect(transcriptionSection).toContain('--stt-scrapecreators-lang')
  expect(documentSection).toContain('--format')
  expect(documentSection).toContain('--primary-ocr')
  expect(articleSection).toContain('--url-request-timeout-ms')
  expect(articleSection).toContain('--url-request-attempts')
  expect(batchSection).toContain('--batch-limit')
  expect(epubSection).toContain('--epub-bun')
  expect(transcriptVideoSection).toContain('--transcript-video')
  expect(transcriptVideoSection).toContain('--transcript-result')
  expect(transcriptVideoSection).toContain('--transcript-text')
  expect(pricingSection).toContain('--price')
  expect(result.stdout).toContain('--batch-limit')
  expect(result.stdout).toContain('--batch-all')
  expect(result.stdout).toContain('--batch-concurrency')
  expect(result.stdout).toContain('--provider')
  expect(result.stdout).toContain('--all-providers')
  expect(result.stdout).not.toContain('--all-stt')
  expect(result.stdout).not.toContain('--all-ocr')
  expect(result.stdout).not.toContain('--all-url')
  expect(result.stdout).not.toContain('--grok-stt')
  expect(result.stdout).not.toContain('--glm-ocr')
  expect(result.stdout).toContain('--stt-scrapecreators-lang')
  expect(result.stdout).not.toContain('--cloudflare-stt')
  expect(result.stdout).toContain('--provider-concurrency')
  expect(result.stdout).toContain('--local-concurrency')
  expect(result.stdout).not.toContain('--ocr-provider-concurrency')
  expect(result.stdout).not.toContain('--url-provider-concurrency')
  expect(result.stdout).toContain('--url-request-timeout-ms')
  expect(result.stdout).toContain('--url-request-attempts')
  expect(result.stdout).toContain('--transcript-video')
  expect(result.stdout).toContain('--transcript-result')
  expect(result.stdout).toContain('--transcript-text')
})

test('download help exposes media preservation flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'download', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(getFlagGroupSection(result.stdout, 'Document Options')).toContain('--password')
  const mediaSection = getFlagGroupSection(result.stdout, 'Media Download Options')
  expect(mediaSection).toContain('--keep-original-media')
  expect(mediaSection).toContain('--best-quality')
  expect(mediaSection).toContain('--flat-batch')
  expect(getFlagGroupSection(result.stdout, 'Article Extraction')).toContain('--url-provider')
  expect(getFlagGroupSection(result.stdout, 'Batch Processing')).toContain('--batch-limit')
  expect(result.stdout).toContain('--keep-original-media')
  expect(result.stdout).toContain('--best-quality')
  expect(result.stdout).toContain('--flat-batch')
})

test('setup help omits removed focused cloud setup flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'setup', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(result.stdout).not.toContain('--cloudflare')
})

test('benchmark help exposes TTS voice-quality scoring flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'benchmark', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(result.stdout).toContain('--tts')
  expect(result.stdout).toContain('--tts-input-text')
  expect(result.stdout).toContain('--tts-mode')
  expect(result.stdout).toContain('--tts-roundtrip-dir')
  expect(result.stdout).toContain('--tts-metric-fixtures')
  expect(result.stdout).toContain('--tts-audio-judge-model')
  expect(result.stdout).toContain('gpt-audio')
  expect(result.stdout).toContain('--tts-keep-temp')
})

test('benchmark help exposes image quality scoring flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'benchmark', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(result.stdout).toContain('--image')
  expect(result.stdout).toContain('--image-judge-model')
  expect(result.stdout).toContain('gpt-5.5')
})

test('benchmark help exposes video quality scoring flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'benchmark', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(result.stdout).toContain('--video')
  expect(result.stdout).toContain('--video-judge-model')
  expect(result.stdout).toContain('gpt-5.5')
})

test('tts help exposes hosted TTS provider flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'tts', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(getFlagGroupSection(result.stdout, 'Provider Selection')).toContain('--provider')
  expect(getFlagGroupSection(result.stdout, 'Provider Selection')).toContain('--provider-concurrency')
  expect(getFlagGroupSection(result.stdout, 'TTS Options')).toContain('--tts-voice')
  expect(getFlagGroupSection(result.stdout, 'MiniMax TTS')).toContain('--minimax-tts-language-boost')
  expect(getFlagGroupSection(result.stdout, 'OpenAI TTS')).toContain('--openai-tts-consent-id')
  expect(getFlagGroupSection(result.stdout, 'Deepgram TTS')).toContain('--deepgram-tts-sample-rate')
  expect(getFlagGroupSection(result.stdout, 'Speechify TTS')).toContain('--speechify-tts-voice-locale')
  expect(getFlagGroupSection(result.stdout, 'Hume TTS')).toContain('--hume-tts-voice-provider')
  expect(getFlagGroupSection(result.stdout, 'Gemini TTS')).toContain('--gemini-speaker-1-name')
  expect(getFlagGroupSection(result.stdout, 'Multi-Speaker / Dialogue')).toContain('--tts-dialogue-format')
  expect(getFlagGroupSection(result.stdout, 'ElevenLabs TTS')).toContain('--elevenlabs-tts-stability')
  expect(getFlagGroupSection(result.stdout, 'Pricing')).toContain('--price')
  expect(getFlagGroupSection(result.stdout, 'Output')).toContain('--output-dir')
  expect(result.stdout).toContain('--provider')
  expect(result.stdout).toContain('--all-providers')
  expect(result.stdout).toContain('--provider-concurrency')
  expect(result.stdout).toContain('--local-concurrency')
  expect(result.stdout).toContain('--tts-voice')
  expect(result.stdout).toContain('--tts-speed')
  expect(result.stdout).toContain('--tts-language')
  expect(result.stdout).toContain('--tts-ref-audio')
  expect(result.stdout).toContain('--tts-voice-name')
  expect(result.stdout).toContain('--tts-consent-audio')
  expect(result.stdout).toContain('--tts-consent-language')
  expect(result.stdout).toContain('--tts-consent-name')
  expect(result.stdout).toContain('--tts-consent-email')
  expect(result.stdout).toContain('--tts-text-normalization')
  expect(result.stdout).toContain('--tts-instructions')
  expect(result.stdout).not.toContain('--grok-tts  ')
  expect(result.stdout).not.toContain('--grok-tts-voice')
  expect(result.stdout).not.toContain('--grok-tts-language')
  expect(result.stdout).not.toContain('--grok-tts-text-normalization')
  expect(result.stdout).not.toContain('--mistral-tts  ')
  expect(result.stdout).not.toContain('--mistral-tts-voice')
  expect(result.stdout).not.toContain('--mistral-tts-ref-audio')
  expect(result.stdout).not.toContain('--mistral-tts-voice-name')
  expect(result.stdout).not.toContain('--deepgram-tts-encoding')
  expect(result.stdout).toContain('--deepgram-tts-container')
  expect(result.stdout).toContain('--deepgram-tts-bit-rate')
  expect(result.stdout).toContain('--deepgram-tts-sample-rate')
  expect(result.stdout).not.toContain('--deepgram-tts-speed')
  expect(result.stdout).not.toContain('--minimax-tts-voice')
  expect(result.stdout).not.toContain('--minimax-tts-ref-audio')
  expect(result.stdout).not.toContain('--minimax-tts-prompt-audio')
  expect(result.stdout).not.toContain('--minimax-tts-prompt-text')
  expect(result.stdout).not.toContain('--minimax-tts-clone-noise-reduction')
  expect(result.stdout).not.toContain('--minimax-tts-clone-volume-normalization')
  expect(result.stdout).toContain('--minimax-tts-language-boost')
  expect(result.stdout).not.toContain('--minimax-tts-speed')
  expect(result.stdout).toContain('--minimax-tts-volume')
  expect(result.stdout).toContain('--minimax-tts-pitch')
  expect(result.stdout).toContain('--minimax-tts-emotion')
  expect(result.stdout).not.toContain('--minimax-tts-english-normalization')
  expect(result.stdout).toContain('--minimax-tts-pronunciation')
  expect(result.stdout).not.toContain('--openai-tts-instructions')
  expect(result.stdout).not.toContain('--openai-tts-speed')
  expect(result.stdout).not.toContain('--openai-tts-ref-audio')
  expect(result.stdout).toContain('--openai-tts-consent-id')
  expect(result.stdout).not.toContain('--openai-tts-consent-audio')
  expect(result.stdout).not.toContain('--openai-tts-consent-language')
  expect(result.stdout).not.toContain('--openai-tts-consent-name')
  expect(result.stdout).not.toContain('--openai-tts-voice-name')
  expect(result.stdout).not.toContain('--runway-tts')
  expect(result.stdout).not.toContain('--runway-tts-voice')
  expect(result.stdout).not.toContain('--speechify-tts  ')
  expect(result.stdout).not.toContain('--speechify-voice')
  expect(result.stdout).not.toContain('--speechify-tts-audio-format')
  expect(result.stdout).not.toContain('--speechify-tts-language')
  expect(result.stdout).not.toContain('--speechify-tts-ref-audio')
  expect(result.stdout).not.toContain('--speechify-tts-voice-name')
  expect(result.stdout).not.toContain('--speechify-tts-consent-name')
  expect(result.stdout).not.toContain('--speechify-tts-consent-email')
  expect(result.stdout).toContain('--speechify-tts-voice-locale')
  expect(result.stdout).toContain('--speechify-tts-voice-gender')
  expect(result.stdout).not.toContain('--hume-tts  ')
  expect(result.stdout).toContain('--hume-tts-voice-provider')
  expect(result.stdout).not.toContain('--cartesia-tts  ')
  expect(result.stdout).not.toContain('--cartesia-tts-voice')
  expect(result.stdout).not.toContain('--cartesia-tts-language')
  expect(result.stdout).not.toContain('--elevenlabs-tts-output-format')
  expect(result.stdout).not.toContain('--elevenlabs-tts-language-code')
  expect(result.stdout).toContain('--elevenlabs-tts-stability')
  expect(result.stdout).toContain('--elevenlabs-tts-similarity-boost')
  expect(result.stdout).toContain('--elevenlabs-tts-style')
  expect(result.stdout).toContain('--elevenlabs-tts-use-speaker-boost')
  expect(result.stdout).not.toContain('--elevenlabs-tts-speed')
  expect(result.stdout).toContain('--elevenlabs-tts-seed')
  expect(result.stdout).not.toContain('--elevenlabs-tts-text-normalization')
  expect(result.stdout).toContain('--elevenlabs-tts-pronunciation-dictionary-locator')
  expect(result.stdout).toContain('--elevenlabs-tts-optimize-streaming-latency')
})

test('write and config help expose shared selectors and concurrency flags', async () => {
  const writeResult = await runCommand(['src/cli/create-cli.ts', 'write', '--help'], { env: helpEnv })
  const configResult = await runCommand(['src/cli/create-cli.ts', 'config', '--help'], { env: helpEnv })

  expect(writeResult.exitCode).toBe(0)
  expect(configResult.exitCode).toBe(0)
  const pipelineSection = getFlagGroupSection(writeResult.stdout, 'Pipeline Selection')
  expect(pipelineSection).toContain('--provider-concurrency')
  expect(pipelineSection).toContain('--local-concurrency')
  expect(pipelineSection).toContain('--all-providers')
  expect(pipelineSection).toContain('--llm')
  expect(getFlagGroupSection(writeResult.stdout, 'Batch / Download')).toContain('--batch-limit')
  expect(getFlagGroupSection(writeResult.stdout, 'Extraction')).toContain('--ocr-language')
  expect(getFlagGroupSection(writeResult.stdout, 'Writing')).toContain('--prompt')
  expect(getFlagGroupSection(writeResult.stdout, 'TTS Options')).toContain('--tts-voice')
  expect(getFlagGroupSection(writeResult.stdout, 'Step 5 - Image')).toContain('--image-aspect-ratio')
  expect(getFlagGroupSection(writeResult.stdout, 'Step 6 - Video')).toContain('--video-mode')
  expect(getFlagGroupSection(writeResult.stdout, 'Step 7 - Music')).toContain('--music-duration')

  const step7Start = writeResult.stdout.indexOf('\n  Step 7 - Music\n')
  expect(step7Start).toBeGreaterThanOrEqual(0)
  const globalFlagsStart = writeResult.stdout.indexOf('\nGlobal Flags\n', step7Start)
  expect(globalFlagsStart).toBeGreaterThan(step7Start)
  const afterStep7BeforeGlobal = writeResult.stdout.slice(step7Start, globalFlagsStart)
  expect(afterStep7BeforeGlobal).not.toContain('\n  --provider-concurrency')
  expect(afterStep7BeforeGlobal).not.toContain('\n  --local-concurrency')
  expect(afterStep7BeforeGlobal).not.toContain('\n  --all-providers')
  expect(writeResult.stdout).toContain('--provider-concurrency')
  expect(writeResult.stdout).toContain('--local-concurrency')
  expect(writeResult.stdout).toContain('--stt')
  expect(writeResult.stdout).toContain('--ocr')
  expect(writeResult.stdout).toContain('--llm')
  expect(writeResult.stdout).toContain('--tts')
  expect(writeResult.stdout).toContain('--image')
  expect(writeResult.stdout).toContain('--video')
  expect(writeResult.stdout).toContain('--music')
  expect(writeResult.stdout).toContain('--all-providers')
  expect(writeResult.stdout).not.toContain('--llm-provider-concurrency')
  expect(writeResult.stdout).not.toContain('--openai-stt')
  expect(configResult.stdout).toContain('--provider-concurrency')
  expect(configResult.stdout).toContain('--local-concurrency')
  expect(configResult.stdout).toContain('--stt')
  expect(configResult.stdout).toContain('--ocr')
  expect(configResult.stdout).toContain('--llm')
  expect(configResult.stdout).toContain('--tts')
  expect(configResult.stdout).not.toContain('--llm-provider-concurrency')
  expect(configResult.stdout).not.toContain('--openai-stt')
  expect(writeResult.stdout).not.toContain(['MiniMax-M2', '5'].join('.'))
  expect(configResult.stdout).not.toContain(['MiniMax-M2', '5'].join('.'))
})

test('music help includes hosted generation and lyric-video flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'music', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(getFlagGroupSection(result.stdout, 'Provider Selection')).toContain('--provider')
  expect(getFlagGroupSection(result.stdout, 'Hosted Music')).toContain('--duration')
  expect(getFlagGroupSection(result.stdout, 'Hosted Music')).toContain('--lyrics-file')
  expect(getFlagGroupSection(result.stdout, 'Pricing')).toContain('--price')
  expect(getFlagGroupSection(result.stdout, 'Output')).toContain('--output-dir')
  expect(getFlagGroupSection(result.stdout, 'Lyric Video')).toContain('--audio')
  expect(getFlagGroupSection(result.stdout, 'Lyric Video')).toContain('--captions')
  expect(result.stdout).toContain('--provider')
  expect(result.stdout).toContain('--all-providers')
  expect(result.stdout).not.toContain('--elevenlabs-music')
  expect(result.stdout).not.toContain('--minimax-music')
  expect(result.stdout).not.toContain('--gemini-music')
  expect(result.stdout).toContain('--provider-concurrency')
  expect(result.stdout).toContain('--local-concurrency')
  expect(result.stdout).toContain('--duration')
  expect(result.stdout).toContain('--lyrics-file')
  expect(result.stdout).toContain('--instrumental')
  expect(result.stdout).not.toContain('--music-duration')
  expect(result.stdout).not.toContain('--music-lyrics-file')
  expect(result.stdout).toContain('--price')
  expect(result.stdout).toContain('--audio')
  expect(result.stdout).toContain('--captions')
  expect(result.stdout).toContain('--batch')
  expect(result.stdout).toContain('--model')
  expect(result.stdout).toContain('--font')
  expect(result.stdout).toContain('--keep-tmp')
  expect(result.stdout).not.toContain('--openai')
  expect(result.stdout).not.toContain('--prompt')
  expect(result.stdout).not.toContain('--prompt-file')
  expect(result.stdout).not.toContain('--track-list')
})

test('image and video help expose BFL/Reve and remaining video provider flags', async () => {
  const imageResult = await runCommand(['src/cli/create-cli.ts', 'image', '--help'], { env: helpEnv })
  const videoResult = await runCommand(['src/cli/create-cli.ts', 'video', '--help'], { env: helpEnv })

  expect(imageResult.exitCode).toBe(0)
  expect(videoResult.exitCode).toBe(0)
  expect(getFlagGroupSection(imageResult.stdout, 'Provider Selection')).toContain('--provider')
  expect(getFlagGroupSection(imageResult.stdout, 'Image Options')).toContain('--aspect-ratio')
  expect(getFlagGroupSection(imageResult.stdout, 'Image Inputs')).toContain('--input')
  expect(getFlagGroupSection(imageResult.stdout, 'Provider-Specific Image Options')).toContain('--compression')
  expect(getFlagGroupSection(imageResult.stdout, 'Pricing')).toContain('--price')
  expect(getFlagGroupSection(imageResult.stdout, 'Output')).toContain('--output-dir')
  expect(getFlagGroupSection(videoResult.stdout, 'Provider Selection')).toContain('--provider')
  expect(getFlagGroupSection(videoResult.stdout, 'Video Options')).toContain('--mode')
  expect(getFlagGroupSection(videoResult.stdout, 'Video Inputs')).toContain('--input-image')
  expect(getFlagGroupSection(videoResult.stdout, 'Grok Storage Options')).toContain('--grok-video-storage-filename')
  expect(getFlagGroupSection(videoResult.stdout, 'Pricing')).toContain('--price')
  expect(getFlagGroupSection(videoResult.stdout, 'Output')).toContain('--output-dir')
  expect(imageResult.stdout).toContain('gpt-image-2')
  expect(imageResult.stdout).toContain('--provider-concurrency')
  expect(imageResult.stdout).toContain('--local-concurrency')
  expect(imageResult.stdout).toContain('--provider')
  expect(imageResult.stdout).toContain('--aspect-ratio')
  expect(imageResult.stdout).toContain('--size')
  expect(imageResult.stdout).toContain('--quality')
  expect(imageResult.stdout).toContain('--format')
  expect(imageResult.stdout).toContain('--count')
  expect(imageResult.stdout).not.toContain('--image-provider-concurrency')
  expect(imageResult.stdout).not.toContain('--image-size')
  expect(imageResult.stdout).not.toContain('--minimax')
  expect(imageResult.stdout).not.toContain('--runway')
  expect(imageResult.stdout).not.toContain('--gemini-person-generation')
  expect(imageResult.stdout).not.toContain('imagen-4.0')
  expect(imageResult.stdout).not.toContain('--glm')
  expect(imageResult.stdout).not.toContain('--bfl-image')
  expect(imageResult.stdout).not.toContain('--reve-image')
  expect(videoResult.stdout).toContain('--provider-concurrency')
  expect(videoResult.stdout).toContain('--local-concurrency')
  expect(videoResult.stdout).toContain('--mode')
  expect(videoResult.stdout).toContain('--input-image')
  expect(videoResult.stdout).toContain('--last-frame')
  expect(videoResult.stdout).toContain('--reference-image')
  expect(videoResult.stdout).toContain('--input-video')
  expect(videoResult.stdout).not.toContain('--video-mode')
  expect(videoResult.stdout).not.toContain('--video-input-image')
  expect(videoResult.stdout).toContain('--grok-video-storage-filename')
})

test('standalone generation help exposes deterministic output directory flags', async () => {
  for (const command of ['image', 'tts', 'video', 'music'] as const) {
    const result = await runCommand(['src/cli/create-cli.ts', command, '--help'], { env: helpEnv })

    expect(result.exitCode).toBe(0)
    expect(result.stdout).toContain('--output-dir')
    expect(result.stdout).not.toMatch(/--out(?:\s|$)/)
  }

  const writeResult = await runCommand(['src/cli/create-cli.ts', 'write', '--help'], { env: helpEnv })
  expect(writeResult.exitCode).toBe(0)
  expect(writeResult.stdout).toContain('Output format: text|json|tsv|hocr')
  expect(writeResult.stdout).not.toContain('Alias for --output-dir')
})

test('resume help exposes unified multi-target provider selector', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'resume', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(result.stdout).toContain('--provider')
  expect(result.stdout).toContain('--all-providers')
  expect(result.stdout).toContain('--provider-concurrency')
  expect(result.stdout).toContain('--local-concurrency')
  expect(result.stdout).toContain('STT:')
  expect(result.stdout).toContain('OCR:')
  expect(result.stdout).toContain('TTS:')
  expect(result.stdout).toContain('image:')
  expect(result.stdout).toContain('video:')
  expect(result.stdout).toContain('music:')
  expect(result.stdout).toContain('whisper')
  expect(result.stdout).toContain('tesseract')
  expect(result.stdout).toContain('kitten')
  expect(result.stdout).toContain('bfl')
  expect(result.stdout).toContain('runway')
})

test('comic help exposes the generate-images command and page flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'comic', 'generate-images', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(result.stdout).toContain('bun as comic generate-images')
  expect(result.stdout).toContain('bun as comic draft-scenes <script-path> [--only structure|prompt|scene|panel-prompts]')
  expect(result.stdout).toContain('bun as comic generate-images <script-path> [--target images|sketches|both]')
  expect(result.stdout).toContain('NN-SC shorthand')
  expect(result.stdout).toContain('05-01')
  expect(result.stdout).toContain('draft-scenes      Run script markdown to structured script JSON to draft prompt bundles to scene JSON to panel prompt bundles')
  expect(result.stdout).toContain('generate-images   Run panel prompt bundles')
  expect(result.stdout).toContain('--only <stage>')
  expect(result.stdout).toContain('panel-prompts')
  expect(result.stdout).toContain('--panels <all|range|list>')
  expect(result.stdout).toContain('--variation <name[,name...]>')
  expect(result.stdout).toContain('--panels-per-image <n>')
  expect(result.stdout).toContain('Panels per generated image (default: 6)')
  expect(result.stdout).toContain('--grid <columns>x<rows>')
  expect(result.stdout).not.toContain('[--target prompts|images|sketches|both]')
})
