import { expect, test } from 'bun:test'
import { runCommand } from '../../test-utils/test-helpers'

const helpEnv = { NO_COLOR: '1' }

const getSection = (output: string, heading: string, nextHeading?: string): string => {
  const start = output.indexOf(heading)
  expect(start).toBeGreaterThanOrEqual(0)

  const sectionStart = start + heading.length
  const end = nextHeading ? output.indexOf(nextHeading, sectionStart) : output.length
  expect(end).toBeGreaterThan(sectionStart)

  return output.slice(sectionStart, end)
}

test('root help groups setup utilities separately from processing commands', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)

  const setupSection = getSection(result.stdout, '  Setup & Utilities\n', '  Processing & Generation\n')
  const processingSection = getSection(result.stdout, '  Processing & Generation\n')

  expect(setupSection).toContain('    links')
  expect(setupSection).toContain('    setup')
  expect(setupSection).toContain('    resume')
  expect(processingSection).toContain('    write')
  expect(processingSection.indexOf('    video')).toBeLessThan(processingSection.indexOf('    music'))
  expect(processingSection).not.toContain('    lyrics')
  expect(processingSection).not.toContain('    stt')
  expect(processingSection).not.toContain('    ocr')
  expect(processingSection).not.toContain('    links')
  expect(processingSection).not.toContain('    resume')
})

test('extract help exposes shared batch and all-provider flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'extract', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(result.stdout).toContain('--batch-limit')
  expect(result.stdout).toContain('--batch-all')
  expect(result.stdout).toContain('--batch-concurrency')
  expect(result.stdout).toContain('--all-stt')
  expect(result.stdout).toContain('--all-ocr')
  expect(result.stdout).toContain('--all-url')
  expect(result.stdout).toContain('--grok')
  expect(result.stdout).toContain('--scrapecreators')
  expect(result.stdout).not.toContain('--grok-stt')
  expect(result.stdout).not.toContain('--glm-ocr')
  expect(result.stdout).toContain('--scrapecreators-lang')
  expect(result.stdout).not.toContain('--cloudflare-stt')
  expect(result.stdout).toContain('--ocr-provider-concurrency')
  expect(result.stdout).toContain('--ocr-local-concurrency')
  expect(result.stdout).toContain('--url-provider-concurrency')
  expect(result.stdout).toContain('--transcript-video')
  expect(result.stdout).toContain('--transcript-result')
  expect(result.stdout).toContain('--transcript-text')
  expect(result.stdout).not.toContain('--deapi-ocr')
})

test('download help exposes media preservation flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'download', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(result.stdout).toContain('--keep-original-media')
  expect(result.stdout).toContain('--best-quality')
  expect(result.stdout).toContain('--flat-batch')
})

test('setup help exposes focused cloud setup flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'setup', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(result.stdout).toContain('--gcloud')
  expect(result.stdout).toContain('--aws')
  expect(result.stdout).not.toContain('--cloudflare')
})

test('benchmark help exposes TTS voice-quality scoring flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'benchmark', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(result.stdout).toContain('--tts')
  expect(result.stdout).toContain('--tts-input-text')
  expect(result.stdout).toContain('--tts-mode')
  expect(result.stdout).toContain('--tts-roundtrip-dir')
  expect(result.stdout).toContain('--tts-metric-fixtures')
  expect(result.stdout).toContain('--tts-audio-judge-model')
  expect(result.stdout).toContain('gpt-audio')
  expect(result.stdout).toContain('--tts-keep-temp')
})

test('tts help exposes hosted TTS provider flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'tts', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(result.stdout).toContain('--tts-provider-concurrency')
  expect(result.stdout).toContain('--tts-local-concurrency')
  expect(result.stdout).toContain('--grok')
  expect(result.stdout).not.toContain('--grok-tts  ')
  expect(result.stdout).toContain('--grok-tts-voice')
  expect(result.stdout).toContain('--grok-tts-language')
  expect(result.stdout).toContain('--grok-tts-text-normalization')
  expect(result.stdout).toContain('--mistral')
  expect(result.stdout).not.toContain('--mistral-tts  ')
  expect(result.stdout).toContain('--mistral-tts-voice')
  expect(result.stdout).toContain('--mistral-tts-ref-audio')
  expect(result.stdout).toContain('--mistral-tts-voice-name')
  expect(result.stdout).toContain('--deepgram-tts-encoding')
  expect(result.stdout).toContain('--deepgram-tts-container')
  expect(result.stdout).toContain('--deepgram-tts-bit-rate')
  expect(result.stdout).toContain('--deepgram-tts-sample-rate')
  expect(result.stdout).toContain('--deepgram-tts-speed')
  expect(result.stdout).toContain('--minimax-tts-voice')
  expect(result.stdout).not.toContain('--minimax-tts-ref-audio')
  expect(result.stdout).not.toContain('--minimax-tts-prompt-audio')
  expect(result.stdout).not.toContain('--minimax-tts-prompt-text')
  expect(result.stdout).not.toContain('--minimax-tts-clone-noise-reduction')
  expect(result.stdout).not.toContain('--minimax-tts-clone-volume-normalization')
  expect(result.stdout).toContain('--minimax-tts-language-boost')
  expect(result.stdout).toContain('--minimax-tts-speed')
  expect(result.stdout).toContain('--minimax-tts-volume')
  expect(result.stdout).toContain('--minimax-tts-pitch')
  expect(result.stdout).toContain('--minimax-tts-emotion')
  expect(result.stdout).toContain('--minimax-tts-english-normalization')
  expect(result.stdout).toContain('--minimax-tts-pronunciation')
  expect(result.stdout).toContain('--openai-tts-instructions')
  expect(result.stdout).toContain('--openai-tts-speed')
  expect(result.stdout).toContain('--openai-tts-ref-audio')
  expect(result.stdout).toContain('--openai-tts-consent-id')
  expect(result.stdout).toContain('--openai-tts-consent-audio')
  expect(result.stdout).toContain('--openai-tts-consent-language')
  expect(result.stdout).toContain('--openai-tts-consent-name')
  expect(result.stdout).toContain('--openai-tts-voice-name')
  expect(result.stdout).toContain('--deapi')
  expect(result.stdout).not.toContain('--deapi-tts  ')
  expect(result.stdout).toContain('--deapi-tts-ref-audio')
  expect(result.stdout).toContain('--deapi-tts-ref-text')
  expect(result.stdout).toContain('--deapi-tts-language')
  expect(result.stdout).toContain('--deapi-tts-speed')
  expect(result.stdout).toContain('--deapi-tts-format')
  expect(result.stdout).toContain('--deapi-tts-sample-rate')
  expect(result.stdout).toContain('--deapi-tts-instruction')
  expect(result.stdout).not.toContain('--runway-tts')
  expect(result.stdout).not.toContain('--runway-tts-voice')
  expect(result.stdout).toContain('--speechify')
  expect(result.stdout).not.toContain('--speechify-tts  ')
  expect(result.stdout).toContain('--speechify-voice')
  expect(result.stdout).toContain('--speechify-tts-audio-format')
  expect(result.stdout).toContain('--speechify-tts-language')
  expect(result.stdout).toContain('--speechify-tts-ref-audio')
  expect(result.stdout).toContain('--speechify-tts-voice-name')
  expect(result.stdout).toContain('--speechify-tts-consent-name')
  expect(result.stdout).toContain('--speechify-tts-consent-email')
  expect(result.stdout).toContain('--speechify-tts-voice-locale')
  expect(result.stdout).toContain('--speechify-tts-voice-gender')
  expect(result.stdout).toContain('--hume')
  expect(result.stdout).not.toContain('--hume-tts  ')
  expect(result.stdout).toContain('--hume-tts-voice')
  expect(result.stdout).toContain('--hume-tts-voice-provider')
  expect(result.stdout).toContain('--cartesia')
  expect(result.stdout).not.toContain('--cartesia-tts  ')
  expect(result.stdout).toContain('--cartesia-tts-voice')
  expect(result.stdout).toContain('--cartesia-tts-language')
  expect(result.stdout).toContain('--elevenlabs-tts-output-format')
  expect(result.stdout).toContain('--elevenlabs-tts-language-code')
  expect(result.stdout).toContain('--elevenlabs-tts-stability')
  expect(result.stdout).toContain('--elevenlabs-tts-similarity-boost')
  expect(result.stdout).toContain('--elevenlabs-tts-style')
  expect(result.stdout).toContain('--elevenlabs-tts-use-speaker-boost')
  expect(result.stdout).toContain('--elevenlabs-tts-speed')
  expect(result.stdout).toContain('--elevenlabs-tts-seed')
  expect(result.stdout).toContain('--elevenlabs-tts-text-normalization')
  expect(result.stdout).toContain('--elevenlabs-tts-pronunciation-dictionary-locator')
  expect(result.stdout).toContain('--elevenlabs-tts-optimize-streaming-latency')
  expect(result.stdout).toContain('--elevenlabs-tts-pvc-as-ivc')
  expect(result.stdout).toContain('--gcloud')
  expect(result.stdout).not.toContain('--gcloud-tts  ')
  expect(result.stdout).toContain('--gcloud-tts-voice')
  expect(result.stdout).toContain('--gcloud-tts-language')
  expect(result.stdout).toContain('--gcloud-tts-ref-audio')
  expect(result.stdout).toContain('--gcloud-tts-consent-audio')
  expect(result.stdout).toContain('--gcloud-tts-consent-language')
  expect(result.stdout).toContain('--gcloud-tts-voice-cloning-key')
  expect(result.stdout).toContain('--gcloud-tts-voice-cloning-key-out')
})

test('write and config help expose LLM concurrency flags', async () => {
  const writeResult = await runCommand(['src/cli/create-cli.ts', 'write', '--help'], { env: helpEnv })
  const configResult = await runCommand(['src/cli/create-cli.ts', 'config', '--help'], { env: helpEnv })

  expect(writeResult.exitCode).toBe(0)
  expect(configResult.exitCode).toBe(0)
  expect(writeResult.stdout).toContain('--llm-provider-concurrency')
  expect(writeResult.stdout).toContain('--llm-local-concurrency')
  expect(writeResult.stdout).toContain('--glm')
  expect(configResult.stdout).toContain('--llm-provider-concurrency')
  expect(configResult.stdout).toContain('--llm-local-concurrency')
  expect(configResult.stdout).toContain('--glm')
})

test('music help includes hosted generation and lyric-video flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'music', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(result.stdout).toContain('--elevenlabs')
  expect(result.stdout).toContain('--minimax')
  expect(result.stdout).toContain('--gemini')
  expect(result.stdout).not.toContain('--elevenlabs-music')
  expect(result.stdout).not.toContain('--minimax-music')
  expect(result.stdout).not.toContain('--gemini-music')
  expect(result.stdout).toContain('--music-provider-concurrency')
  expect(result.stdout).toContain('--music-local-concurrency')
  expect(result.stdout).toContain('--music-duration')
  expect(result.stdout).toContain('--music-lyrics-file')
  expect(result.stdout).toContain('--price')
  expect(result.stdout).toContain('--audio')
  expect(result.stdout).toContain('--captions')
  expect(result.stdout).toContain('--batch')
  expect(result.stdout).toContain('--model')
  expect(result.stdout).toContain('--font')
  expect(result.stdout).toContain('--keep-tmp')
  expect(result.stdout).not.toContain('--openai')
  expect(result.stdout).not.toContain('--prompt')
  expect(result.stdout).not.toContain('--prompt-file')
  expect(result.stdout).not.toContain('--track-list')
})

test('image and video help expose BFL/deAPI/Reve provider flags', async () => {
  const imageResult = await runCommand(['src/cli/create-cli.ts', 'image', '--help'], { env: helpEnv })
  const videoResult = await runCommand(['src/cli/create-cli.ts', 'video', '--help'], { env: helpEnv })

  expect(imageResult.exitCode).toBe(0)
  expect(videoResult.exitCode).toBe(0)
  expect(imageResult.stdout).toContain('gpt-image-2')
  expect(imageResult.stdout).toContain('--image-provider-concurrency')
  expect(imageResult.stdout).toContain('--image-local-concurrency')
  expect(imageResult.stdout).toContain('--bfl')
  expect(imageResult.stdout).toContain('--deapi')
  expect(imageResult.stdout).toContain('--reve')
  expect(imageResult.stdout).not.toContain('--glm')
  expect(imageResult.stdout).not.toContain('--bfl-image')
  expect(imageResult.stdout).not.toContain('--deapi-image')
  expect(imageResult.stdout).not.toContain('--reve-image')
  expect(videoResult.stdout).toContain('--video-provider-concurrency')
  expect(videoResult.stdout).toContain('--video-local-concurrency')
  expect(videoResult.stdout).toContain('--video-mode')
  expect(videoResult.stdout).toContain('--video-input-image')
  expect(videoResult.stdout).toContain('--video-last-frame')
  expect(videoResult.stdout).toContain('--video-reference-image')
  expect(videoResult.stdout).toContain('--video-input-video')
  expect(videoResult.stdout).toContain('--grok-video-storage-filename')
  expect(videoResult.stdout).toContain('--deapi')
  expect(videoResult.stdout).not.toContain('--deapi-video')
})

test('standalone generation help exposes deterministic output directory flags', async () => {
  for (const command of ['image', 'tts', 'video', 'music'] as const) {
    const result = await runCommand(['src/cli/create-cli.ts', command, '--help'], { env: helpEnv })

    expect(result.exitCode).toBe(0)
    expect(result.stdout).toContain('--output-dir')
    expect(result.stdout).toContain('--out')
  }

  const writeResult = await runCommand(['src/cli/create-cli.ts', 'write', '--help'], { env: helpEnv })
  expect(writeResult.exitCode).toBe(0)
  expect(writeResult.stdout).toContain('Output format: text, json, tsv, hocr')
  expect(writeResult.stdout).not.toContain('Alias for --output-dir')
})

test('comic help exposes the generate-images command and page flags', async () => {
  const result = await runCommand(['src/cli/create-cli.ts', 'comic', 'generate-images', '--help'], { env: helpEnv })

  expect(result.exitCode).toBe(0)
  expect(result.stdout).toContain('bun as comic generate-images')
  expect(result.stdout).toContain('bun as comic draft-scenes <script-path> [--only structure|prompt|scene|panel-prompts]')
  expect(result.stdout).toContain('bun as comic generate-images <script-path> [--target images|sketches|both]')
  expect(result.stdout).toContain('NN-SC shorthand')
  expect(result.stdout).toContain('05-01')
  expect(result.stdout).toContain('draft-scenes      Run script markdown to structured script JSON to draft prompt bundles to scene JSON to panel prompt bundles')
  expect(result.stdout).toContain('generate-images   Run panel prompt bundles')
  expect(result.stdout).toContain('--only <stage>')
  expect(result.stdout).toContain('panel-prompts')
  expect(result.stdout).toContain('--panels <all|range|list>')
  expect(result.stdout).toContain('--variation <name[,name...]>')
  expect(result.stdout).toContain('--panels-per-image <n>')
  expect(result.stdout).toContain('Panels per generated image (default: 6)')
  expect(result.stdout).toContain('--grid <columns>x<rows>')
  expect(result.stdout).not.toContain('[--target prompts|images|sketches|both]')
})
