import {
  SUPPORTED_MISTRAL_OCR_MODELS,
  SUPPORTED_GLM_OCR_MODELS,
  SUPPORTED_KIMI_OCR_MODELS,
  SUPPORTED_OPENAI_OCR_MODELS,
  SUPPORTED_GROK_OCR_MODELS,
  SUPPORTED_ANTHROPIC_OCR_MODELS,
  SUPPORTED_GEMINI_OCR_MODELS,
  SUPPORTED_DEEPINFRA_OCR_MODELS,
  SUPPORTED_AWS_TEXTRACT_MODELS,
  SUPPORTED_GCLOUD_DOCAI_MODELS,
  SUPPORTED_UNSTRUCTURED_OCR_MODELS,
  validateMistralOcrModel,
  validateGlmOcrModel,
  validateKimiOcrModel,
  validateOpenAIOcrModel,
  validateGrokOcrModel,
  validateAnthropicOcrModel,
  validateGeminiOcrModel,
  validateDeepinfraOcrModel,
  validateAwsTextractModel,
  validateGcloudDocaiModel,
  validateUnstructuredOcrModel
} from '~/cli/commands/setup-and-utilities/models/model-options'
import { buildModelDescription } from '~/cli/commands/setup-and-utilities/models/model-validation'
import type { Step2ProviderRegistryEntry } from '~/types'
import { booleanProvider, modelProvider } from './entry-builders'

export const STEP2_OCR_PROVIDER_REGISTRY = [
  booleanProvider({
    step: 'ocr',
    modality: 'document',
    flagName: 'tesseract-ocr',
    targetService: 'tesseract',
    providerSpecProvider: 'tesseract',
    bootstrapProviderId: 'tesseract',
    configKey: 'tesseract',
    allShortcut: 'all-ocr',
    runtimeKey: 'useTesseract',
    model: 'tesseract',
    description: 'Use Tesseract OCR (default local OCR engine for PDF/image; forces OCR mode for EPUB and office documents)'
  }),
  booleanProvider({
    step: 'ocr',
    modality: 'document',
    flagName: 'ocrmypdf',
    targetService: 'ocrmypdf',
    providerSpecProvider: 'ocrmypdf',
    bootstrapProviderId: 'ocrmypdf',
    configKey: 'ocrmypdf',
    allShortcut: 'all-ocr',
    runtimeKey: 'useOcrmypdf',
    model: 'ocrmypdf',
    description: 'Use OCRmyPDF engine for extraction (auto-converts EPUB/image inputs to PDF; installed lazily on first use)'
  }),
  booleanProvider({
    step: 'ocr',
    modality: 'document',
    flagName: 'paddle-ocr',
    targetService: 'paddle-ocr',
    providerSpecProvider: 'paddle-ocr',
    bootstrapProviderId: 'paddle-ocr',
    configKey: 'paddleOcr',
    allShortcut: 'all-ocr',
    runtimeKey: 'usePaddleOcr',
    model: 'paddle-ocr',
    description: 'Use PaddleOCR engine for extraction (PDF, EPUB, image; installed lazily on first use)'
  }),
  modelProvider({
    step: 'ocr',
    modality: 'document',
    flagName: 'mistral-ocr',
    targetService: 'mistral',
    providerSpecProvider: 'mistral-ocr',
    bootstrapProviderId: 'mistral-ocr',
    configKey: 'mistralOcr',
    allShortcut: 'all-ocr',
    runtimeModelsKey: 'mistralOcrModels',
    runtimeModelKey: 'mistralOcrModel',
    supportedModels: SUPPORTED_MISTRAL_OCR_MODELS,
    validateModel: validateMistralOcrModel,
    description: buildModelDescription('Mistral OCR model', SUPPORTED_MISTRAL_OCR_MODELS)
  }),
  modelProvider({
    step: 'ocr',
    modality: 'document',
    flagName: 'glm-ocr',
    targetService: 'glm',
    providerSpecProvider: 'glm-ocr',
    bootstrapProviderId: 'glm-ocr',
    configKey: 'glmOcr',
    allShortcut: 'all-ocr',
    runtimeModelsKey: 'glmOcrModels',
    runtimeModelKey: 'glmOcrModel',
    supportedModels: SUPPORTED_GLM_OCR_MODELS,
    validateModel: validateGlmOcrModel,
    description: buildModelDescription('GLM OCR model', SUPPORTED_GLM_OCR_MODELS)
  }),
  modelProvider({
    step: 'ocr',
    modality: 'document',
    flagName: 'kimi-ocr',
    targetService: 'kimi',
    providerSpecProvider: 'kimi-ocr',
    bootstrapProviderId: 'kimi-ocr',
    configKey: 'kimiOcr',
    allShortcut: 'all-ocr',
    runtimeModelsKey: 'kimiOcrModels',
    runtimeModelKey: 'kimiOcrModel',
    supportedModels: SUPPORTED_KIMI_OCR_MODELS,
    validateModel: validateKimiOcrModel,
    description: buildModelDescription('Kimi OCR model', SUPPORTED_KIMI_OCR_MODELS)
  }),
  modelProvider({
    step: 'ocr',
    modality: 'document',
    flagName: 'openai-ocr',
    targetService: 'openai',
    providerSpecProvider: 'openai-ocr',
    bootstrapProviderId: 'openai-ocr',
    configKey: 'openaiOcr',
    allShortcut: 'all-ocr',
    runtimeModelsKey: 'openaiOcrModels',
    runtimeModelKey: 'openaiOcrModel',
    supportedModels: SUPPORTED_OPENAI_OCR_MODELS,
    validateModel: validateOpenAIOcrModel,
    description: buildModelDescription('OpenAI OCR model', SUPPORTED_OPENAI_OCR_MODELS)
  }),
  modelProvider({
    step: 'ocr',
    modality: 'document',
    flagName: 'grok-ocr',
    targetService: 'grok',
    providerSpecProvider: 'grok-ocr',
    bootstrapProviderId: 'grok-ocr',
    configKey: 'grokOcr',
    allShortcut: 'all-ocr',
    runtimeModelsKey: 'grokOcrModels',
    runtimeModelKey: 'grokOcrModel',
    supportedModels: SUPPORTED_GROK_OCR_MODELS,
    validateModel: validateGrokOcrModel,
    description: buildModelDescription('Grok OCR model', SUPPORTED_GROK_OCR_MODELS)
  }),
  modelProvider({
    step: 'ocr',
    modality: 'document',
    flagName: 'anthropic-ocr',
    targetService: 'anthropic',
    providerSpecProvider: 'anthropic-ocr',
    bootstrapProviderId: 'anthropic-ocr',
    configKey: 'anthropicOcr',
    allShortcut: 'all-ocr',
    runtimeModelsKey: 'anthropicOcrModels',
    runtimeModelKey: 'anthropicOcrModel',
    supportedModels: SUPPORTED_ANTHROPIC_OCR_MODELS,
    validateModel: validateAnthropicOcrModel,
    description: buildModelDescription('Anthropic OCR model', SUPPORTED_ANTHROPIC_OCR_MODELS)
  }),
  modelProvider({
    step: 'ocr',
    modality: 'document',
    flagName: 'gemini-ocr',
    targetService: 'gemini',
    providerSpecProvider: 'gemini-ocr',
    bootstrapProviderId: 'gemini-ocr',
    configKey: 'geminiOcr',
    allShortcut: 'all-ocr',
    runtimeModelsKey: 'geminiOcrModels',
    runtimeModelKey: 'geminiOcrModel',
    supportedModels: SUPPORTED_GEMINI_OCR_MODELS,
    validateModel: validateGeminiOcrModel,
    description: buildModelDescription('Gemini OCR model', SUPPORTED_GEMINI_OCR_MODELS)
  }),
  modelProvider({
    step: 'ocr',
    modality: 'document',
    flagName: 'deepinfra-ocr',
    targetService: 'deepinfra',
    providerSpecProvider: 'deepinfra-ocr',
    bootstrapProviderId: 'deepinfra-ocr',
    configKey: 'deepinfraOcr',
    allShortcut: 'all-ocr',
    runtimeModelsKey: 'deepinfraOcrModels',
    runtimeModelKey: 'deepinfraOcrModel',
    supportedModels: SUPPORTED_DEEPINFRA_OCR_MODELS,
    validateModel: validateDeepinfraOcrModel,
    description: buildModelDescription('DeepInfra OCR model', SUPPORTED_DEEPINFRA_OCR_MODELS)
  }),
  modelProvider({
    step: 'ocr',
    modality: 'document',
    flagName: 'aws-textract',
    targetService: 'aws-textract',
    providerSpecProvider: 'aws-textract',
    bootstrapProviderId: 'aws-textract',
    configKey: 'awsTextract',
    allShortcut: 'all-ocr',
    runtimeModelsKey: 'awsTextractModels',
    runtimeModelKey: 'awsTextractModel',
    supportedModels: SUPPORTED_AWS_TEXTRACT_MODELS,
    validateModel: validateAwsTextractModel,
    description: buildModelDescription('AWS Textract model', SUPPORTED_AWS_TEXTRACT_MODELS)
  }),
  modelProvider({
    step: 'ocr',
    modality: 'document',
    flagName: 'gcloud-docai',
    targetService: 'gcloud-docai',
    providerSpecProvider: 'gcloud-docai',
    bootstrapProviderId: 'gcloud-docai',
    configKey: 'gcloudDocai',
    allShortcut: 'all-ocr',
    runtimeModelsKey: 'gcloudDocaiModels',
    runtimeModelKey: 'gcloudDocaiModel',
    supportedModels: SUPPORTED_GCLOUD_DOCAI_MODELS,
    validateModel: validateGcloudDocaiModel,
    description: buildModelDescription('Google Cloud Document AI model', SUPPORTED_GCLOUD_DOCAI_MODELS)
  }),
  modelProvider({
    step: 'ocr',
    modality: 'document',
    flagName: 'unstructured-ocr',
    targetService: 'unstructured',
    providerSpecProvider: 'unstructured-ocr',
    bootstrapProviderId: 'unstructured-ocr',
    configKey: 'unstructuredOcr',
    allShortcut: 'all-ocr',
    runtimeModelsKey: 'unstructuredOcrModels',
    runtimeModelKey: 'unstructuredOcrModel',
    supportedModels: SUPPORTED_UNSTRUCTURED_OCR_MODELS,
    validateModel: validateUnstructuredOcrModel,
    description: buildModelDescription('Unstructured OCR model', SUPPORTED_UNSTRUCTURED_OCR_MODELS)
  })
] as const satisfies readonly Step2ProviderRegistryEntry[]
