import {
  SUPPORTED_WHISPER_MODELS,
  SUPPORTED_GCLOUD_STT_MODELS,
  SUPPORTED_AWS_STT_MODELS,
  SUPPORTED_DEEPINFRA_STT_MODELS,
  SUPPORTED_DEAPI_STT_MODELS,
  SUPPORTED_ELEVENLABS_STT_MODELS,
  SUPPORTED_DEEPGRAM_STT_MODELS,
  SUPPORTED_SONIOX_STT_MODELS,
  SUPPORTED_SPEECHMATICS_STT_MODELS,
  SUPPORTED_REV_STT_MODELS,
  SUPPORTED_GROQ_STT_MODELS,
  SUPPORTED_GROK_STT_MODELS,
  SUPPORTED_MISTRAL_STT_MODELS,
  SUPPORTED_ASSEMBLYAI_STT_MODELS,
  SUPPORTED_GLADIA_STT_MODELS,
  SUPPORTED_HAPPYSCRIBE_STT_MODELS,
  SUPPORTED_SUPADATA_STT_MODELS,
  SUPPORTED_OPENAI_STT_MODELS,
  SUPPORTED_GEMINI_STT_MODELS,
  SUPPORTED_GLM_STT_MODELS,
  SUPPORTED_TOGETHER_STT_MODELS,
  SUPPORTED_CLOUDFLARE_STT_MODELS,
  validateWhisperModel,
  validateGcloudSttModel,
  validateAwsSttModel,
  validateDeepinfraSttModel,
  validateDeapiSttModel,
  validateElevenlabsSttModel,
  validateDeepgramSttModel,
  validateSonioxSttModel,
  validateSpeechmaticsSttModel,
  validateRevSttModel,
  validateGroqSttModel,
  validateGrokSttModel,
  validateMistralSttModel,
  validateAssemblyaiSttModel,
  validateGladiaSttModel,
  validateHappyscribeSttModel,
  validateSupadataSttModel,
  validateOpenaiSttModel,
  validateGeminiSttModel,
  validateGlmSttModel,
  validateTogetherSttModel,
  validateCloudflareSttModel
} from '~/cli/commands/setup-and-utilities/models/model-options'
import { buildModelDescription } from '~/cli/commands/setup-and-utilities/models/model-validation'
import type { Step2ProviderRegistryEntry } from '~/types'
import { booleanProvider, modelProvider } from './entry-builders'

export const STEP2_STT_PROVIDER_REGISTRY = [
  booleanProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'reverb-stt',
    targetService: 'reverb',
    providerSpecProvider: 'reverb',
    bootstrapProviderId: 'reverb',
    configKey: 'reverb',
    allShortcut: 'all-stt',
    runtimeKey: 'useReverb',
    model: 'reverb',
    description: 'Use Reverb ASR for transcription'
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'gcloud-stt',
    targetService: 'gcloud',
    providerSpecProvider: 'gcloud',
    bootstrapProviderId: 'gcloud-stt',
    configKey: 'gcloudStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'gcloudSttModels',
    runtimeModelKey: 'gcloudSttModel',
    supportedModels: SUPPORTED_GCLOUD_STT_MODELS,
    validateModel: validateGcloudSttModel,
    description: buildModelDescription('Google Cloud STT model', SUPPORTED_GCLOUD_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'aws-stt',
    targetService: 'aws',
    providerSpecProvider: 'aws',
    bootstrapProviderId: 'aws-stt',
    configKey: 'awsStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'awsSttModels',
    runtimeModelKey: 'awsSttModel',
    supportedModels: SUPPORTED_AWS_STT_MODELS,
    validateModel: validateAwsSttModel,
    description: buildModelDescription('AWS Transcribe STT model', SUPPORTED_AWS_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'deepinfra-stt',
    targetService: 'deepinfra',
    providerSpecProvider: 'deepinfra',
    bootstrapProviderId: 'deepinfra-stt',
    configKey: 'deepinfraStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'deepinfraSttModels',
    runtimeModelKey: 'deepinfraSttModel',
    supportedModels: SUPPORTED_DEEPINFRA_STT_MODELS,
    validateModel: validateDeepinfraSttModel,
    description: buildModelDescription('DeepInfra Whisper STT model (API, billed)', SUPPORTED_DEEPINFRA_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'deapi-stt',
    targetService: 'deapi',
    providerSpecProvider: 'deapi',
    bootstrapProviderId: 'deapi-stt',
    configKey: 'deapiStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'deapiSttModels',
    runtimeModelKey: 'deapiSttModel',
    supportedModels: SUPPORTED_DEAPI_STT_MODELS,
    validateModel: validateDeapiSttModel,
    description: buildModelDescription('deAPI STT model', SUPPORTED_DEAPI_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'elevenlabs-stt',
    targetService: 'elevenlabs',
    providerSpecProvider: 'elevenlabs',
    bootstrapProviderId: 'elevenlabs-stt',
    configKey: 'elevenlabsStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'elevenlabsSttModels',
    runtimeModelKey: 'elevenlabsSttModel',
    supportedModels: SUPPORTED_ELEVENLABS_STT_MODELS,
    validateModel: validateElevenlabsSttModel,
    description: buildModelDescription('ElevenLabs STT model', SUPPORTED_ELEVENLABS_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'deepgram-stt',
    targetService: 'deepgram',
    providerSpecProvider: 'deepgram',
    bootstrapProviderId: 'deepgram-stt',
    configKey: 'deepgramStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'deepgramSttModels',
    runtimeModelKey: 'deepgramSttModel',
    supportedModels: SUPPORTED_DEEPGRAM_STT_MODELS,
    validateModel: validateDeepgramSttModel,
    description: buildModelDescription('Deepgram STT model', SUPPORTED_DEEPGRAM_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'soniox-stt',
    targetService: 'soniox',
    providerSpecProvider: 'soniox',
    bootstrapProviderId: 'soniox-stt',
    configKey: 'sonioxStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'sonioxSttModels',
    runtimeModelKey: 'sonioxSttModel',
    supportedModels: SUPPORTED_SONIOX_STT_MODELS,
    validateModel: validateSonioxSttModel,
    description: buildModelDescription('Soniox STT model', SUPPORTED_SONIOX_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'speechmatics-stt',
    targetService: 'speechmatics',
    providerSpecProvider: 'speechmatics',
    bootstrapProviderId: 'speechmatics-stt',
    configKey: 'speechmaticsStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'speechmaticsSttModels',
    runtimeModelKey: 'speechmaticsSttModel',
    supportedModels: SUPPORTED_SPEECHMATICS_STT_MODELS,
    validateModel: validateSpeechmaticsSttModel,
    description: buildModelDescription('Speechmatics STT model', SUPPORTED_SPEECHMATICS_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'rev-stt',
    targetService: 'rev',
    providerSpecProvider: 'rev',
    bootstrapProviderId: 'rev-stt',
    configKey: 'revStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'revSttModels',
    runtimeModelKey: 'revSttModel',
    supportedModels: SUPPORTED_REV_STT_MODELS,
    validateModel: validateRevSttModel,
    description: buildModelDescription('Rev STT model', SUPPORTED_REV_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'groq-stt',
    targetService: 'groq',
    providerSpecProvider: 'groq',
    bootstrapProviderId: 'groq-stt',
    configKey: 'groqStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'groqSttModels',
    runtimeModelKey: 'groqSttModel',
    supportedModels: SUPPORTED_GROQ_STT_MODELS,
    validateModel: validateGroqSttModel,
    description: buildModelDescription('Groq Whisper STT model (API, billed)', SUPPORTED_GROQ_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'grok-stt',
    targetService: 'grok',
    providerSpecProvider: 'grok',
    bootstrapProviderId: 'grok-stt',
    configKey: 'grokStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'grokSttModels',
    runtimeModelKey: 'grokSttModel',
    supportedModels: SUPPORTED_GROK_STT_MODELS,
    validateModel: validateGrokSttModel,
    description: buildModelDescription('xAI Grok STT model', SUPPORTED_GROK_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'mistral-stt',
    targetService: 'mistral',
    providerSpecProvider: 'mistral',
    bootstrapProviderId: 'mistral-stt',
    configKey: 'mistralStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'mistralSttModels',
    runtimeModelKey: 'mistralSttModel',
    supportedModels: SUPPORTED_MISTRAL_STT_MODELS,
    validateModel: validateMistralSttModel,
    description: buildModelDescription('Mistral STT model', SUPPORTED_MISTRAL_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'assemblyai-stt',
    targetService: 'assemblyai',
    providerSpecProvider: 'assemblyai',
    bootstrapProviderId: 'assemblyai-stt',
    configKey: 'assemblyaiStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'assemblyaiSttModels',
    runtimeModelKey: 'assemblyaiSttModel',
    supportedModels: SUPPORTED_ASSEMBLYAI_STT_MODELS,
    validateModel: validateAssemblyaiSttModel,
    description: buildModelDescription('AssemblyAI STT model', SUPPORTED_ASSEMBLYAI_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'gladia-stt',
    targetService: 'gladia',
    providerSpecProvider: 'gladia',
    bootstrapProviderId: 'gladia-stt',
    configKey: 'gladiaStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'gladiaSttModels',
    runtimeModelKey: 'gladiaSttModel',
    supportedModels: SUPPORTED_GLADIA_STT_MODELS,
    validateModel: validateGladiaSttModel,
    description: buildModelDescription('Gladia STT model', SUPPORTED_GLADIA_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'happyscribe-stt',
    targetService: 'happyscribe',
    providerSpecProvider: 'happyscribe',
    bootstrapProviderId: 'happyscribe-stt',
    configKey: 'happyscribeStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'happyscribeSttModels',
    runtimeModelKey: 'happyscribeSttModel',
    supportedModels: SUPPORTED_HAPPYSCRIBE_STT_MODELS,
    validateModel: validateHappyscribeSttModel,
    description: buildModelDescription('Happy Scribe automatic STT model (fixed en-US only)', SUPPORTED_HAPPYSCRIBE_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'supadata-stt',
    targetService: 'supadata',
    providerSpecProvider: 'supadata',
    bootstrapProviderId: 'supadata-stt',
    configKey: 'supadataStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'supadataSttModels',
    runtimeModelKey: 'supadataSttModel',
    supportedModels: SUPPORTED_SUPADATA_STT_MODELS,
    validateModel: validateSupadataSttModel,
    description: buildModelDescription('Supadata STT mode', SUPPORTED_SUPADATA_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'openai-stt',
    targetService: 'openai-stt',
    providerSpecProvider: 'openai-stt',
    bootstrapProviderId: 'openai-stt',
    configKey: 'openaiStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'openaiSttModels',
    runtimeModelKey: 'openaiSttModel',
    supportedModels: SUPPORTED_OPENAI_STT_MODELS,
    validateModel: validateOpenaiSttModel,
    description: buildModelDescription('OpenAI STT model', SUPPORTED_OPENAI_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'gemini-stt',
    targetService: 'gemini-stt',
    providerSpecProvider: 'gemini-stt',
    bootstrapProviderId: 'gemini-stt',
    configKey: 'geminiStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'geminiSttModels',
    runtimeModelKey: 'geminiSttModel',
    supportedModels: SUPPORTED_GEMINI_STT_MODELS,
    validateModel: validateGeminiSttModel,
    description: buildModelDescription('Gemini STT model', SUPPORTED_GEMINI_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'glm-stt',
    targetService: 'glm-stt',
    providerSpecProvider: 'glm-stt',
    bootstrapProviderId: 'glm-stt',
    configKey: 'glmStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'glmSttModels',
    runtimeModelKey: 'glmSttModel',
    supportedModels: SUPPORTED_GLM_STT_MODELS,
    validateModel: validateGlmSttModel,
    description: buildModelDescription('GLM STT model', SUPPORTED_GLM_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'together-stt',
    targetService: 'together',
    providerSpecProvider: 'together',
    bootstrapProviderId: 'together-stt',
    configKey: 'togetherStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'togetherSttModels',
    runtimeModelKey: 'togetherSttModel',
    supportedModels: SUPPORTED_TOGETHER_STT_MODELS,
    validateModel: validateTogetherSttModel,
    description: buildModelDescription('Together Whisper STT model (API, billed)', SUPPORTED_TOGETHER_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'cloudflare-stt',
    targetService: 'cloudflare',
    providerSpecProvider: 'cloudflare',
    bootstrapProviderId: 'cloudflare-stt',
    configKey: 'cloudflareStt',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'cloudflareSttModels',
    runtimeModelKey: 'cloudflareSttModel',
    supportedModels: SUPPORTED_CLOUDFLARE_STT_MODELS,
    validateModel: validateCloudflareSttModel,
    description: buildModelDescription('Cloudflare Workers AI STT model (API, billed)', SUPPORTED_CLOUDFLARE_STT_MODELS)
  }),
  modelProvider({
    step: 'stt',
    modality: 'media',
    flagName: 'whisper-stt',
    targetService: 'whisper',
    providerSpecProvider: 'whisper',
    bootstrapProviderId: 'whisper',
    configKey: 'whisper',
    allShortcut: 'all-stt',
    runtimeModelsKey: 'whisperModels',
    runtimeModelKey: 'whisperModel',
    supportedModels: SUPPORTED_WHISPER_MODELS,
    validateModel: validateWhisperModel,
    description: 'Local whisper.cpp model (free): tiny|base|small|medium|large-v3-turbo'
  })
] as const satisfies readonly Step2ProviderRegistryEntry[]
