import { getOutputRoot } from '~/cli/commands/process-steps/output-root'
import { isStep2BooleanProviderSelected } from '~/cli/commands/process-steps/step-2-extract/step-2-shared/provider-registry'
import type { BuildOptsDefaults, OutputFormat, RuntimeOptions } from '~/types'
import {
  parseFloatWithDefault,
  parseIntWithDefault,
  parseOptionalNumberFlag,
  parseOptionalPositiveIntFlag,
  parsePdfChapterMode,
  readBatchOrder,
  readBooleanFlag,
  readOptionalStringFlag,
  readOptionalStringListFlag,
  readStringFlag
} from '../options/flag-readers'
import { parseRepeatableModelFlagOccurrences, readAllShortcutFlags, resolveStep2SelectionOrigins } from '../options/model-flag-selection'
import { readRuntimeModelOptions } from '../options/model-options'
import { readInjectedConfigFlags } from './config-flags'
import { resolveLocalConcurrency, resolveProviderConcurrency } from './concurrency'
import { readPromptFlags } from './prompt-options'
import { resolveTargetCounts } from './target-counts'
import { buildTtsOptions } from './tts-options'
import { HOSTED_URL_ARTICLE_BACKEND_CONCURRENCY_TARGET, resolveUrlOptions } from './url-options'

export { REPEATABLE_MODEL_FLAGS, normalizeModelFlagOccurrences, parseRepeatableModelFlagOccurrences } from '../options/model-flag-selection'

export const buildOptsFromFlags = (
  skipLLM: boolean,
  flags: Record<string, unknown>,
  _doubleDashArgs: string[] = [],
  defaults: BuildOptsDefaults = {},
  explicitFlags: Set<string> = new Set(),
  rawArgs: string[] = []
): RuntimeOptions => {
  void _doubleDashArgs
  const rawFlagArgs = rawArgs.includes('--') ? rawArgs.slice(0, rawArgs.indexOf('--')) : rawArgs
  const rawModelOccurrences = parseRepeatableModelFlagOccurrences(rawFlagArgs)

  const mergedFlags: Record<string, unknown> = { ...flags }
  const allShortcutFlags = readAllShortcutFlags(mergedFlags)
  const configuredFlags = readInjectedConfigFlags(mergedFlags)
  const outputFormat = readStringFlag(mergedFlags, 'out', 'json')
  const normalizedOut: OutputFormat = outputFormat === 'text' || outputFormat === 'tsv' || outputFormat === 'hocr' ? outputFormat : 'json'
  const epubLengthThousands = parseOptionalPositiveIntFlag(readOptionalStringFlag(mergedFlags, 'length'), 'length')
  const pdfChapterMode = parsePdfChapterMode(readOptionalStringFlag(mergedFlags, 'pdf-chapter-mode'))

  const modelOptions = readRuntimeModelOptions(mergedFlags, rawModelOccurrences, allShortcutFlags, defaults)
  const {
    whisperModels,
    whisperModel,
    gcloudSttModels,
    gcloudSttModel,
    awsSttModels,
    awsSttModel,
    deepinfraSttModels,
    deepinfraSttModel,
    deapiSttModels,
    deapiSttModel,
    groqSttModels,
    groqSttModel,
    grokSttModels,
    grokSttModel,
    elevenlabsSttModels,
    elevenlabsSttModel,
    deepgramSttModels,
    deepgramSttModel,
    sonioxSttModels,
    sonioxSttModel,
    speechmaticsSttModels,
    speechmaticsSttModel,
    revSttModels,
    revSttModel,
    mistralSttModels,
    mistralSttModel,
    assemblyaiSttModels,
    assemblyaiSttModel,
    gladiaSttModels,
    gladiaSttModel,
    happyscribeSttModels,
    happyscribeSttModel,
    supadataSttModels,
    supadataSttModel,
    scrapecreatorsSttModels,
    scrapecreatorsSttModel,
    openaiSttModels,
    openaiSttModel,
    geminiSttModels,
    geminiSttModel,
    glmSttModels,
    glmSttModel,
    togetherSttModels,
    togetherSttModel,
    mistralOcrModels,
    mistralOcrModel,
    glmOcrModels,
    glmOcrModel,
    kimiOcrModels,
    kimiOcrModel,
    openaiOcrModels,
    openaiOcrModel,
    anthropicOcrModels,
    anthropicOcrModel,
    geminiOcrModels,
    geminiOcrModel,
    deepinfraOcrModels,
    deepinfraOcrModel,
    awsTextractModels,
    awsTextractModel,
    gcloudDocaiModels,
    gcloudDocaiModel,
    unstructuredOcrModels,
    unstructuredOcrModel,
    llamaModels,
    llamaModel,
    openaiModels,
    openaiModel,
    groqModels,
    groqModel,
    geminiModels,
    geminiModel,
    anthropicModels,
    anthropicModel,
    minimaxModels,
    minimaxModel,
    grokModels,
    grokModel,
    glmModels,
    glmModel,
    kimiModels,
    kimiModel,
    geminiImageModels,
    geminiImageModel,
    openaiImageModels,
    openaiImageModel,
    minimaxImageModels,
    minimaxImageModel,
    glmImageModels,
    glmImageModel,
    grokImageModels,
    grokImageModel,
    runwayImageModels,
    runwayImageModel,
    bflImageModels,
    bflImageModel,
    deapiImageModels,
    deapiImageModel,
    elevenlabsMusicModels,
    elevenlabsMusicModel,
    minimaxMusicModels,
    minimaxMusicModel,
    deapiMusicModels,
    deapiMusicModel,
    geminiMusicModels,
    geminiMusicModel,
    geminiVideoModels,
    geminiVideoModel,
    minimaxVideoModels,
    minimaxVideoModel,
    glmVideoModels,
    glmVideoModel,
    grokVideoModels,
    grokVideoModel,
    runwayVideoModels,
    runwayVideoModel,
    deapiVideoModels,
    deapiVideoModel
  } = modelOptions
  const allUrlSelected = allShortcutFlags['all-url']
  const urlOptions = resolveUrlOptions(mergedFlags, allUrlSelected)
  const useReverb = isStep2BooleanProviderSelected('reverb-stt', mergedFlags, allShortcutFlags)
  const step2SelectionOrigins = resolveStep2SelectionOrigins(mergedFlags, explicitFlags, rawModelOccurrences, allShortcutFlags)
  const whisperExplicit = step2SelectionOrigins['whisper-stt'] === 'explicit' || step2SelectionOrigins['whisper-stt'] === 'all-shortcut'
  const useTesseract = isStep2BooleanProviderSelected('tesseract-ocr', mergedFlags, allShortcutFlags)
  const useOcrmypdf = isStep2BooleanProviderSelected('ocrmypdf', mergedFlags, allShortcutFlags)
  const usePaddleOcr = isStep2BooleanProviderSelected('paddle-ocr', mergedFlags, allShortcutFlags)
  const {
    hostedOcrTargetCount,
    hostedLlmTargetCount,
    hostedTtsTargetCount,
    hostedImageTargetCount,
    hostedVideoTargetCount,
    hostedMusicTargetCount,
  } = resolveTargetCounts(modelOptions)

  return {
    outputRootDir: getOutputRoot(),
    configPath: readOptionalStringFlag(mergedFlags, 'config-path'),
    useReverb,
    youtubeCaptions: readBooleanFlag(mergedFlags, 'youtube-captions'),
    whisperExplicit,
    step2SelectionOrigins,
    llamaModels,
    llamaModel,
    openaiModels,
    openaiModel,
    groqModels,
    groqModel,
    geminiModels,
    geminiModel,
    anthropicModels,
    anthropicModel,
    minimaxModels,
    minimaxModel,
    grokModels,
    grokModel,
    glmModels,
    glmModel,
    kimiModels,
    kimiModel,
    whisperModels,
    whisperModel,
    gcloudSttModels,
    gcloudSttModel,
    awsSttModels,
    awsSttModel,
    awsRegion: readOptionalStringFlag(mergedFlags, 'aws-region'),
    awsBucket: readOptionalStringFlag(mergedFlags, 'aws-bucket'),
    deepinfraSttModels,
    deepinfraSttModel,
    deapiSttModels,
    deapiSttModel,
    groqSttModels,
    groqSttModel,
    grokSttModels,
    grokSttModel,
    elevenlabsSttModels,
    elevenlabsSttModel,
    deepgramSttModels,
    deepgramSttModel,
    sonioxSttModels,
    sonioxSttModel,
    speechmaticsSttModels,
    speechmaticsSttModel,
    revSttModels,
    revSttModel,
    mistralSttModels,
    mistralSttModel,
    assemblyaiSttModels,
    assemblyaiSttModel,
    gladiaSttModels,
    gladiaSttModel,
    happyscribeSttModels,
    happyscribeSttModel,
    happyscribeOrganizationId: readOptionalStringFlag(mergedFlags, 'happyscribe-organization-id'),
    supadataSttModels,
    supadataSttModel,
    scrapecreatorsSttModels,
    scrapecreatorsSttModel,
    openaiSttModels,
    openaiSttModel,
    geminiSttModels,
    geminiSttModel,
    glmSttModels,
    glmSttModel,
    togetherSttModels,
    togetherSttModel,
    supadataLang: readOptionalStringFlag(mergedFlags, 'supadata-lang'),
    scrapecreatorsLang: readOptionalStringFlag(mergedFlags, 'scrapecreators-lang') ?? 'en',
    diarizationSpeakerCount: parseOptionalPositiveIntFlag(readOptionalStringFlag(mergedFlags, 'speaker-count'), 'speaker-count'),
    sttProviderConcurrency: Math.max(1, parseIntWithDefault(readOptionalStringFlag(mergedFlags, 'stt-provider-concurrency'), 2)),
    sttLocalConcurrency: Math.max(1, parseIntWithDefault(readOptionalStringFlag(mergedFlags, 'stt-local-concurrency'), 1)),
    sttSegmentConcurrency: Math.max(1, parseIntWithDefault(readOptionalStringFlag(mergedFlags, 'stt-segment-concurrency'), 2)),
    sttPreflightConcurrency: Math.max(1, parseIntWithDefault(readOptionalStringFlag(mergedFlags, 'stt-preflight-concurrency'), 4)),
    ocrProviderConcurrency: resolveProviderConcurrency(mergedFlags, 'ocr-provider-concurrency', allShortcutFlags['all-ocr'], hostedOcrTargetCount, explicitFlags, configuredFlags),
    ocrLocalConcurrency: resolveLocalConcurrency(mergedFlags, 'ocr-local-concurrency'),
    llmProviderConcurrency: resolveProviderConcurrency(mergedFlags, 'llm-provider-concurrency', allShortcutFlags['all-llm'], hostedLlmTargetCount, explicitFlags, configuredFlags),
    llmLocalConcurrency: resolveLocalConcurrency(mergedFlags, 'llm-local-concurrency'),
    ttsProviderConcurrency: resolveProviderConcurrency(mergedFlags, 'tts-provider-concurrency', allShortcutFlags['all-tts'], hostedTtsTargetCount, explicitFlags, configuredFlags),
    ttsLocalConcurrency: resolveLocalConcurrency(mergedFlags, 'tts-local-concurrency'),
    imageProviderConcurrency: resolveProviderConcurrency(mergedFlags, 'image-provider-concurrency', allShortcutFlags['all-image'], hostedImageTargetCount, explicitFlags, configuredFlags),
    imageLocalConcurrency: resolveLocalConcurrency(mergedFlags, 'image-local-concurrency'),
    videoProviderConcurrency: resolveProviderConcurrency(mergedFlags, 'video-provider-concurrency', allShortcutFlags['all-video'], hostedVideoTargetCount, explicitFlags, configuredFlags),
    videoLocalConcurrency: resolveLocalConcurrency(mergedFlags, 'video-local-concurrency'),
    musicProviderConcurrency: resolveProviderConcurrency(mergedFlags, 'music-provider-concurrency', allShortcutFlags['all-music'], hostedMusicTargetCount, explicitFlags, configuredFlags),
    musicLocalConcurrency: resolveLocalConcurrency(mergedFlags, 'music-local-concurrency'),
    refreshCache: readBooleanFlag(mergedFlags, 'refresh-cache'),
    noCache: readBooleanFlag(mergedFlags, 'no-cache'),
    price: readBooleanFlag(mergedFlags, 'price'),
    allowOverBudget: readBooleanFlag(mergedFlags, 'allow-over-budget'),
    reverbVerbatimicity: parseFloatWithDefault(readOptionalStringFlag(mergedFlags, 'reverb-verbatimicity'), 0.5),
    split: readBooleanFlag(mergedFlags, 'split'),
    skipLLM,
    dpi: parseIntWithDefault(readOptionalStringFlag(mergedFlags, 'dpi'), 300),
    lang: readStringFlag(mergedFlags, 'lang', 'eng'),
    psm: parseIntWithDefault(readOptionalStringFlag(mergedFlags, 'psm'), 3),
    oem: parseIntWithDefault(readOptionalStringFlag(mergedFlags, 'oem'), 1),
    out: normalizedOut,
    password: readOptionalStringFlag(mergedFlags, 'password'),
    pageSeparator: readOptionalStringFlag(mergedFlags, 'page-separator'),
    preserveSpaces: readBooleanFlag(mergedFlags, 'preserve-spaces'),
    rotate: parseIntWithDefault(readOptionalStringFlag(mergedFlags, 'rotate'), 0),
    useTesseract,
    useOcrmypdf,
    usePaddleOcr,
    mistralOcrModels,
    mistralOcrModel,
    glmOcrModels,
    glmOcrModel,
    kimiOcrModels,
    kimiOcrModel,
    openaiOcrModels,
    openaiOcrModel,
    anthropicOcrModels,
    anthropicOcrModel,
    geminiOcrModels,
    geminiOcrModel,
    deepinfraOcrModels,
    deepinfraOcrModel,
    awsTextractModels,
    awsTextractModel,
    gcloudDocaiModels,
    gcloudDocaiModel,
    unstructuredOcrModels,
    unstructuredOcrModel,
    primaryOcr: readOptionalStringFlag(mergedFlags, 'primary-ocr'),
    epubChapterFiles: readBooleanFlag(mergedFlags, 'chapters'),
    epubChunkLimitChars: epubLengthThousands === undefined ? undefined : epubLengthThousands * 1000,
    pdfChapterMode,
    useEpubBun: readBooleanFlag(mergedFlags, 'epub-bun'),
    useEpubCalibre: readBooleanFlag(mergedFlags, 'epub-calibre'),
    ...urlOptions,
    urlProviderConcurrency: resolveProviderConcurrency(
      mergedFlags,
      'url-provider-concurrency',
      allUrlSelected,
      HOSTED_URL_ARTICLE_BACKEND_CONCURRENCY_TARGET,
      explicitFlags,
      configuredFlags
    ),
    batchLimit: parseIntWithDefault(readOptionalStringFlag(mergedFlags, 'batch-limit'), 5),
    batchAll: readBooleanFlag(mergedFlags, 'batch-all'),
    batchOrder: readBatchOrder(mergedFlags),
    batchConcurrency: Math.max(1, parseIntWithDefault(readOptionalStringFlag(mergedFlags, 'batch-concurrency'), 1)),
    keepOriginalMedia: readBooleanFlag(mergedFlags, 'keep-original-media'),
    bestQuality: readBooleanFlag(mergedFlags, 'best-quality'),
    flatBatch: readBooleanFlag(mergedFlags, 'flat-batch'),
    ytDlpPassthroughArgs: undefined,
    prompts: readPromptFlags(mergedFlags),
    promptFile: readOptionalStringFlag(mergedFlags, 'prompt-file'),
    textInput: readBooleanFlag(mergedFlags, 'text-input'),
    renderedText: readBooleanFlag(mergedFlags, 'rendered-text'),
    renderedOutDir: readOptionalStringFlag(mergedFlags, 'rendered-out-dir'),
    trackList: readOptionalStringFlag(mergedFlags, 'track-list'),
    promptMd: readBooleanFlag(mergedFlags, 'prompt-md'),
    ...buildTtsOptions(mergedFlags, rawFlagArgs, modelOptions),
    geminiImageModels,
    geminiImageModel,
    openaiImageModels,
    openaiImageModel,
    minimaxImageModels,
    minimaxImageModel,
    glmImageModels,
    glmImageModel,
    grokImageModels,
    grokImageModel,
    runwayImageModels,
    runwayImageModel,
    bflImageModels,
    bflImageModel,
    deapiImageModels,
    deapiImageModel,
    imageAspectRatio: readOptionalStringFlag(mergedFlags, 'image-aspect-ratio'),
    imageSize: readOptionalStringFlag(mergedFlags, 'image-size'),
    imageQuality: readOptionalStringFlag(mergedFlags, 'image-quality'),
    imageFormat: readOptionalStringFlag(mergedFlags, 'image-format'),
    imageBackground: readOptionalStringFlag(mergedFlags, 'image-background'),
    imageCount: parseOptionalPositiveIntFlag(readOptionalStringFlag(mergedFlags, 'image-count'), 'image-count'),
    imageInputs: readOptionalStringListFlag(mergedFlags, 'image-input'),
    imageMask: readOptionalStringFlag(mergedFlags, 'image-mask'),
    imageResponseMode: readOptionalStringFlag(mergedFlags, 'image-response-mode'),
    geminiPersonGeneration: readOptionalStringFlag(mergedFlags, 'gemini-person-generation'),
    geminiSearchGrounding: readBooleanFlag(mergedFlags, 'gemini-search-grounding') ? true : undefined,
    imageCompression: parseOptionalNumberFlag(readOptionalStringFlag(mergedFlags, 'image-compression'), 'image-compression', {
      min: 0,
      max: 100,
      integer: true
    }),
    elevenlabsMusicModels,
    elevenlabsMusicModel,
    minimaxMusicModels,
    minimaxMusicModel,
    deapiMusicModels,
    deapiMusicModel,
    geminiMusicModels,
    geminiMusicModel,
    musicDuration: (() => {
      const v = readOptionalStringFlag(mergedFlags, 'music-duration')
      if (v === undefined) return undefined
      const n = parseInt(v, 10)
      return Number.isFinite(n) ? n : undefined
    })(),
    musicLyricsFile: readOptionalStringFlag(mergedFlags, 'music-lyrics-file'),
    musicInstrumental: readBooleanFlag(mergedFlags, 'music-instrumental'),
    geminiVideoModels,
    geminiVideoModel,
    minimaxVideoModels,
    minimaxVideoModel,
    glmVideoModels,
    glmVideoModel,
    grokVideoModels,
    grokVideoModel,
    runwayVideoModels,
    runwayVideoModel,
    deapiVideoModels,
    deapiVideoModel,
    allVideo: allShortcutFlags['all-video'],
    videoDuration: (() => {
      const v = readOptionalStringFlag(mergedFlags, 'video-duration')
      if (v === undefined) return undefined
      const n = parseInt(v, 10)
      return Number.isFinite(n) ? n : undefined
    })(),
    videoSize: readOptionalStringFlag(mergedFlags, 'video-size'),
    videoAspectRatio: readOptionalStringFlag(mergedFlags, 'video-aspect-ratio'),
    videoResolution: readOptionalStringFlag(mergedFlags, 'video-resolution'),
    videoMode: readOptionalStringFlag(mergedFlags, 'video-mode'),
    videoInputImage: readOptionalStringFlag(mergedFlags, 'video-input-image'),
    videoLastFrame: readOptionalStringFlag(mergedFlags, 'video-last-frame'),
    videoReferenceImages: readOptionalStringListFlag(mergedFlags, 'video-reference-image'),
    videoInputVideo: readOptionalStringFlag(mergedFlags, 'video-input-video'),
    grokVideoStorageFilename: readOptionalStringFlag(mergedFlags, 'grok-video-storage-filename'),
    grokVideoStorageExpiresAfter: parseOptionalNumberFlag(readOptionalStringFlag(mergedFlags, 'grok-video-storage-expires-after'), 'grok-video-storage-expires-after', {
      min: 1,
      max: 2592000,
      integer: true
    }),

    markdown: readBooleanFlag(mergedFlags, 'markdown'),
    save: readBooleanFlag(mergedFlags, 'save'),
  }
}
