export {
  DEFAULT_SPLIT_SEGMENT_DURATION_MINUTES,
  GLADIA_MAX_ATTACHMENT_BYTES,
  GROQ_MAX_ATTACHMENT_BYTES,
  SPEECHMATICS_MAX_ATTACHMENT_BYTES,
  REV_MAX_ATTACHMENT_BYTES,
  ensureSttTargetSetup,
  getSttEngineCapabilities,
  isPayloadTooLargeTranscriptionError,
  mergeSplitTranscriptionChunks,
  resolveDiarizationOptions,
  resolveEffectiveSegmentConcurrency,
  resolveEffectiveSplitSegmentDurationMinutes,
  resolveSttSplitPolicy,
  resolveTranscriptionSplitDecision,
  shouldRetrySplitTranscriptionAfterError,
  shouldSplitTranscriptionInput,
  stt,
  sttTarget
} from './run-stt'
